import streamlit as st
import joblib

# Load model and vectorizer
vectorizer = joblib.load('vectorizer.pkl')
model = joblib.load('logistic_model.pkl')

# Streamlit UI
st.set_page_config(page_title="AI Text Detector", page_icon="🤖", layout="centered")

st.markdown(
    """
    <h2 style='text-align: center; color: #4CAF50;'>🤖 AI vs Human Text Detector</h2>
    <p style='text-align: center;'>Enter a sentence to check if it was written by a human or generated by AI.</p>
    """,
    unsafe_allow_html=True
)

# Input
user_input = st.text_area("Enter your sentence here:", height=150)

# Predict on button click
if st.button("Check"):
    if user_input.strip() == "":
        st.warning("Please enter a sentence before submitting.")
    else:
        transformed_input = vectorizer.transform([user_input])
        prediction = model.predict(transformed_input)

        if prediction[0] == 1:
            st.error("🔍 This text is likely **AI-generated**.")
        else:
            st.success("✅ This text is likely **Human-written**.")
